# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5df0ab13863bfee1608d5ac38d04f1238cf3bc69eabb02de4c331dd836be18add80f261a0947153de9a693397fe07fa7db6ad17f838ae69bc5feb0134312b0aa

test:
  secret_key_base: fa961fac053c4ef24120394bcd107b85567fd74c2262045772a429e43f0dd6b4674a0dc22ebebc6281cc7b4960db0cfe4217dcdc05141b1615cdb99b489fff26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
